version: '3.9'

services:
  react:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /usr/src/app/webapp
    container_name: demeter-webapp
    volumes:
      - ./:/usr/src/app/webapp
