version: '3.9'
services:
  react:
    volumes:
      - .:/workspace:cached
      - vscode-exts:/root/.vscode-server/extensions
      - vscode-exts-insiders:/root/.vscode-server/extensions
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 8080:8080 # This is used by webpack server

volumes:
  vscode-exts:
  vscode-exts-insiders:
